[package]
name = "nanofrann"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
rand = "0.9.0-alpha.2"
kiddo = "4.2.0"
kd-tree = "0.6.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
opt-level = 3
strip = "debuginfo"